### ISSUE TITLE
Isso devia funcionar 

### ISSUE THREAD

**Issue by gmfc** [giovannigv/iot-ionic#1]
https://github.com/giovannigv/iot-ionic/blob/7e034b400c8f9445c4293eeeeb978a7f1c795b05/src/pages/home/consulta.ts#L23

**Comment by gmfc** [comment]
Algum followup ou posso fechar a issue @giovannigv ?

**Comment by giovannigv** [comment]
ele funciona normalmente, menos na rede da universidade.
